internalName: tyv

locales:
  en:
    name: &bundleName "Tuvinian Keyboards"
    description: "Mobile OS keyboards for the Tuvinian language from the Divvun group at UiT."
  nb:
    name: "Tuvinian tastatur"
    description: "Mobiltastatur for Tuvinian fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga 치rktala코 universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts:
  - tyv-mob
  - tyv-mac
  - tyv-win

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.tyv
    icon: images/tyv-icon.pdf
    keyStore: $GTPRIV/admin/dev-accounts/dev_keys/sami_keyboard.keystore
    keyAlias: sami_keyboard

  ios: &AppleID
    codeSignId: "Developer ID Installer: The University of Tromso (2K5J2584NX)"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.tyv
    bundleName: *bundleName
    icon: images/tyv-icon.png

  osx:
    <<: *AppleID
    icon: images/tyv-keyboard-menu-icon.png
    version: 0.1.0
    resources: doc

  win:
    appName: *bundleName
    version: 0.1.0
    url: "http://divvun.no"
    uuid: "C66B1700-2037-4254-86B6-284F1B2A6BFC"
