locales:
  en:
    name: Tuvan Keyboards
    description: Keyboards for the Tuvan language from the Divvun group at UiT.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
